site_name: Glide 文档
pages:
- 首页: index.md
- 入门指南: getting-started.md
- 配置文件(glide.yaml): glide.yaml.md
- 版本和范围: versions.md
- 锁文件(Lock file): glide.lock.md
- 命令: commands.md
- 导入解析: resolving-imports.md
- Vendor 目录: vendor.md
- 插件: plugins.md
- 常见问题: faq.md
theme: readthedocs
